import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect } from 'react';
import aboutbackground from '../public/aboutbackground.jpeg';
import styles from '../styles/Home.module.css';

const mainTextStyles = css`
  margin: 1%;
  margin-top: 5%;
  color: grey;
`;

const backgroundImageStyles = css`
  width: 90%;
  padding: 5%;
`;

type Props = {
  refreshUserProfile: () => Promise<void>;
};
export default function Home(props: Props) {
  useEffect(() => {
    props.refreshUserProfile().catch(() => console.log('refresh user profile'));
  }, [props]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div css={backgroundImageStyles}>
          <Image
            src={aboutbackground}
            alt="bridges and canals in Manchester at night"
            // width="600"
            // height="400"
          />
        </div>
        <section css={mainTextStyles}>
          <div>
            Locoda are a Drum and Bass Producer / DJ Duo from Manchester, UK
          </div>
          <br />
          <div>
            Locoda delivered a thundering debut in the form of “Closer”
            featuring the stunning vocals of Tricia McTeague who has previously
            worked with the likes of Paul van Dyk, Schiller, and Giuseppe
            Ottaviani as well as touring with Nile Rogers, Natalie Imbruglia and
            more.
          </div>
          <br />
          <div>
            In a time when we have all been wanting to dance carefree, “Closer”
            really sets the tone for the return to festivals and the dancefloor
            with its uplifting lyrics about being back together, back with
            big-room DnB vibes to deliver a real highlight to any set. The duo
            debuted the track at the One In The Woods festival supporting Sub
            Focus, Friction, Grooverider and more, and got it's premiere on BBC
            Radio 1 - Rene LaVice DnB Show.
          </div>
          <br />
          <Link href="/">Radio 1 DnB Show </Link>
        </section>
      </main>

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
      {/* </a>
      </footer> */}
    </div>
  );
}
