import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect } from 'react';
import styles from '../styles/Home.module.css';

const mainVideoStyles = css`
  margin: 10%;
  margin-top: 5%;
`;

type Props = {
  refreshUserProfile: () => Promise<void>;
};
export default function Home(props: Props) {
  useEffect(() => {
    props.refreshUserProfile().catch(() => console.log('refresh user profile'));
  }, [props]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section css={mainVideoStyles}>
          <h1>Releases:</h1>
        </section>
      </main>
    </div>
  );
}
