import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect } from 'react';
import darkbackground1 from '../public/darkbackground1.jpeg';
import styles from '../styles/Home.module.css';

const bgWrap = css`
  position: fixed;
  height: 100vh;
  width: 100vw;
  overflow: hidden;
  z-index: -1;
  // border: 1px green solid;
`;

const bgText = css`
  background-color: none;
  margin: 0;
  font-size: 2rem;
  line-height: 3rem;
  padding-left: 10%;
  padding-top: 40vh;
  text-shadow: 1px 1px 1px #3c5c5e;
  z-index: 0;
  opacity: 0.75;
  color: white;
`;

type Props = {
  refreshUserProfile: () => Promise<void>;
};

export default function Contact(props: Props) {
  useEffect(() => {
    props.refreshUserProfile().catch(() => console.log('refresh user profile'));
  }, [props]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div css={bgWrap}>
        <Image
          alt="Mountains"
          src={darkbackground1}
          layout="fill"
          objectFit="cover"
          quality={100}
        />
      </div>
      <p css={bgText}>
        <h2>Contact and Bookings:</h2>
        For Booking and Inquires please contact:
        <br />
        locodabookings@email.com
      </p>
    </div>
  );
}
