import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect } from 'react';
import darkbackground1 from '../public/darkbackground1.jpeg';
import styles from '../styles/Home.module.css';

const mainVideoStyles = css`
  display: flex;
  align-items: center;
  flex-direction: column;
`;

const backgroundImageStyles = css`
  width: 100%;
  z-index: -5;
`;

const mainStyles = css`
  // background-color: grey;
`;

const headerTextStyles = css`
  display: flex;
  align-items: center;
  flex-direction: column;
  // border: 2px green solid;
`;

const footerTextStyles = css`
  display: flex;
  font-size: 10px;
  justify-content: center;
  align-items: center;
  flex-direction: row;
`;

type Props = {
  refreshUserProfile: () => Promise<void>;
};
export default function Home(props: Props) {
  useEffect(() => {
    props.refreshUserProfile().catch(() => console.log('refresh user profile'));
  }, [props]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={mainStyles}>
        <br />
        <br />
        <br />
        <section css={headerTextStyles}>
          <h1>CLOSER OUT NOW</h1>
          <br />
          <h2>on Code Recordings</h2>
          <br />
        </section>

        <section css={mainVideoStyles}>
          {/* <div ccs={backgroundImageStyles}>
            <Image src={darkbackground1} />
          </div> */}
          <iframe
            width="1020"
            height="530"
            src="https://www.youtube-nocookie.com/embed/HwwtvZ45PB4"
            title="YouTube video player"
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
          />
        </section>
        <br />
        <section css={footerTextStyles}>
          <div>
            <Link css={footerTextStyles} href="https://ingrv.es/closer-bek-3">
              Stream |
            </Link>
          </div>
          <div>
            <Link href="https://www.beatport.com/release/closer/3708354">
              | Beatport |
            </Link>
          </div>
          <div>
            <Link href="https://coderecs.bandcamp.com/album/closer-closer-instrumental">
              | Bandcamp
            </Link>
          </div>
        </section>
      </main>
    </div>
  );
}
