// import 'boxicons';
import { css } from '@emotion/react';
import Head from 'next/head';
// import Image from 'next/image';
import Link from 'next/link';
import { useEffect } from 'react';
// react-youtube used due to eslint problems with requiring sandboxes for iframes
import YouTube from 'react-youtube';

// import darkbackground1 from '../public/darkbackground1.jpeg';
// import styles from '../styles/Home.module.css';

const mainVideoStyles = css`
  display: flex;
  align-items: center;
  flex-direction: column;
`;

const mainStyles = css`
  // background-color: grey;
`;

const headerTextStyles = css`
  display: flex;
  align-items: center;
  flex-direction: column;
  color: white;
  // border: 2px green solid;
`;

const footerTextStyles = css`
  display: flex;
  font-size: 13px;
  justify-content: center;
  align-items: center;
  flex-direction: row;
  color: white;
`;

type Props = {
  refreshUserProfile: () => Promise<void>;
};

export default function Home(props: Props) {
  useEffect(() => {
    props.refreshUserProfile().catch(() => console.log('refresh user profile'));
  }, [props]);

  const onPlayerReady: YouTubeProps['onReady'] = (event: any) => {
    // access to player in all event handlers via event.target
    event.target.pauseVideo();
  };

  const opts: YouTubeProps['opts'] = {
    height: '480',
    width: '880',
    playerVars: {
      // https://developers.google.com/youtube/player_parameters
      autoplay: 0,
    },
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={mainStyles}>
        <br />
        <br />
        <br />
        <section css={headerTextStyles}>
          <h1>CLOSER OUT NOW</h1>
          <br />
          <h2>on Code Recordings</h2>
          <br />
        </section>

        <section css={mainVideoStyles}>
          <br />
          <YouTube videoId="HwwtvZ45PB4" opts={opts} onReady={onPlayerReady} />
        </section>
        <br />
        <section css={footerTextStyles}>
          <div>
            <Link css={footerTextStyles} href="https://ingrv.es/closer-bek-3">
              Stream |
            </Link>
          </div>
          <div>
            <Link href="https://www.beatport.com/release/closer/3708354">
              | Beatport |
            </Link>
          </div>
          <div>
            <Link href="https://coderecs.bandcamp.com/album/closer-closer-instrumental">
              | Bandcamp
            </Link>
          </div>
          {/* <div>
            <Link href="https://api.mixcloud.com/spartacus/party-time/embed-html/">
              something
            </Link>
          </div> */}
        </section>
        {/* <box-icon type="solid" name="hot"></box-icon> */}
      </main>
    </div>
  );
}
